Feature/yamlsupport
OpenTOSCA/container pull request #274
Opened 2022-03-23 13:46 UTC by nyuuyn

#### Short Description
Enable general usage of yaml tosca applications

#### Proposed Changes
  * Enable importing YAML csars via given winery importers
  *  Enable PlanBuilder to work with YAML csars
  * Probably refactor code that is hard-wired to the XML spec of TOSCA
  * Write Test Case for a YAML CSAR from https://github.com/radon-h2020/radon-particles (Propably DeploymentTestAgent template)

2022-03-23 13:56 UTC, nyuuyn commented
[DeploymentTestAgent.csar.zip](https://github.com/OpenTOSCA/container/files/8333588/DeploymentTestAgent.csar.zip)

Here is a small example, maybe not deployable, test csar for this PR.
Don't forget to rename it from *.csar.zip to *.csar as github doesn't allow .csar endings to be uploaded

2022-03-29 12:22 UTC, nyuuyn commented
They whole PR is heavily depending on the following PR: https://github.com/eclipse/winery/pull/665

2022-03-29 14:49 UTC, lharzenetter requested changes

2022-03-29 14:49 UTC, lharzenetter commented on org.opentosca.container.core/src/main/resources/application.properties
> +org.opentosca.container.hostname=192.168.0.239
revert these changes

2022-03-29 14:49 UTC, lharzenetter commented
Is the PR in eclipse ready to be merged?

2023-03-24 10:26 UTC, closed without merging