fixes issue with generting scaling plans again although they are already available
OpenTOSCA/container pull request #299
Opened 2022-08-18 13:50 UTC by nyuuyn

**Fixes**: #294 
However it seems it didn't work only for scale out plans, but thats fixed now. Can't reproduce for other plans.
Tested with the following CSAR: https://drive.google.com/file/d/1V0nwhw_axdsohr83MCnj48JLhfEsYcUe/view?usp=sharing

2022-08-18 14:33 UTC, wederbn commented on org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELScaleOutProcessBuilder.java
> +                    isAlreadyAvailable = true;
break the loop here?

2022-08-18 14:36 UTC, lharzenetter requested changes
What @wederbn said.

2022-08-18 17:02 UTC, nyuuyn commented on org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELScaleOutProcessBuilder.java
> +                    isAlreadyAvailable = true;
fixed

2022-08-19 06:26 UTC, lharzenetter approved these changes
LGTM

2022-08-19 07:14 UTC, wederbn approved these changes
LGTM

2022-08-19 07:14 UTC, merged